name:                 interpretor
version:              0.1.0.0
visibility:           public
id:                   interpretor-0.1.0.0-CIEEk7fBgZ6FgXjLhe3j8t
key:                  interpretor-0.1.0.0-CIEEk7fBgZ6FgXjLhe3j8t
abi:                  3d6513768c88ecf59787f66a7f36d0c5
exposed:              True
exposed-modules:      Ast Lexer Parser Token Utils
import-dirs:
    /home/arla/dev/interpretor/.stack-work/install/x86_64-linux-tinfo6/aa58564c18976a12add44406ba88a5976a5e010aea6291ccc2ea1b3c38c418ff/9.0.2/lib/x86_64-linux-ghc-9.0.2/interpretor-0.1.0.0-CIEEk7fBgZ6FgXjLhe3j8t

library-dirs:
    /home/arla/dev/interpretor/.stack-work/install/x86_64-linux-tinfo6/aa58564c18976a12add44406ba88a5976a5e010aea6291ccc2ea1b3c38c418ff/9.0.2/lib/x86_64-linux-ghc-9.0.2/interpretor-0.1.0.0-CIEEk7fBgZ6FgXjLhe3j8t

dynamic-library-dirs:
    /home/arla/dev/interpretor/.stack-work/install/x86_64-linux-tinfo6/aa58564c18976a12add44406ba88a5976a5e010aea6291ccc2ea1b3c38c418ff/9.0.2/lib/x86_64-linux-ghc-9.0.2

data-dir:
    /home/arla/dev/interpretor/.stack-work/install/x86_64-linux-tinfo6/aa58564c18976a12add44406ba88a5976a5e010aea6291ccc2ea1b3c38c418ff/9.0.2/share/x86_64-linux-ghc-9.0.2/interpretor-0.1.0.0

hs-libraries:         HSinterpretor-0.1.0.0-CIEEk7fBgZ6FgXjLhe3j8t
depends:              base-4.15.1.0 containers-0.6.4.1
haddock-interfaces:
    /home/arla/dev/interpretor/.stack-work/install/x86_64-linux-tinfo6/aa58564c18976a12add44406ba88a5976a5e010aea6291ccc2ea1b3c38c418ff/9.0.2/doc/interpretor-0.1.0.0/interpretor.haddock

haddock-html:
    /home/arla/dev/interpretor/.stack-work/install/x86_64-linux-tinfo6/aa58564c18976a12add44406ba88a5976a5e010aea6291ccc2ea1b3c38c418ff/9.0.2/doc/interpretor-0.1.0.0
