name: test-workflow 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run Scanner/Ast Tests
      run: make bt
    - name: LLVM Backend test
      run: make llt

