name: test-workflow 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build 
      run: make b
    - name: Run Frontend Tests
      run: make t
    - name: LLVM Backend test
      run: make llt

