name: test-workflow 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM
      run: |

          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-get update
          sudo apt-get install -y llvm-16 llvm-16-dev clang-16
          llvm-config --version
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build 
      run: make b
    - name: Run Frontend Tests
      run: make t
    - name: LLVM Backend test
      run: make llt

