name: test-workflow 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM
      run: |
          sudo apt-get update
          sudo apt-get install -y llvm llvm-dev llvm-tools clang
          llvm-config --version
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build 
      run: make b
    - name: Run Frontend Tests
      run: make t
    - name: LLVM Backend test
      run: make llt

