name: test-workflow 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh 
          sudo ./llvm.sh 16.0
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build 
      run: make b
    - name: Run Frontend Tests
      run: make t
    - name: LLVM Backend test
      run: make llt

